### ISSUE TITLE
[fi] Incorrect large ordinal numbers

### ISSUE THREAD

**Issue by tjhietala** [Numbertext/libnumbertext#19]
Finnish ordinal numbers from one million and up are incorrect when the number starts with 1. Examples: 

1000000 outputs "ensimmäinenmiljoonas", should be "miljoonas".
1000000000 outputs "ensimmäinenmiljardis", should be "miljardis".
1000000000000 outputs "ensimmäinenbiljoonas", should be "biljoonas".

**Comment by laszlonemeth** [comment]
Fixed in commit 3e7263900ab7611e4e9cf3b3ce45cabdf1de53cc.
Thanks for your bug report!
