### ISSUE TITLE
licensing (license versions) unclear.

### ISSUE THREAD

**Issue by reneengelhard** [Numbertext/libnumbertext#2]
Hi,

currently packaging libnumbertext for Debian for LibreOffice 6.1.

README says:

> License: LGPL/BSD dual-license, 2009-2018 (C) László Németh (nemeth at numbertext dot org)
>
> Numbertext language data (Soros programs):
>
> LGPL/BSD dual-license, 2009-2018 (C) László Németh et al. (see AUTHORS)
>
> Serbian modules:
>
> CC/LGPL/BSD tri-license, 2009 (C) Goran Rakić (grakic at devbase dot net)

CC is mentioned in data/sr.sor as Creative Commons 3.0 Attribution - Share Alike license.
So far OK, but which versions of the LGPL? and which BSD one? (3-clause I assume?). Maybe you even mean the MIT/Expat one? Or is this LGPL-3+ as one can deduce from 

> # and relicensed under GNU Lesser General Public License as published by
> # the Free Software Foundation, either version 3 of the License, or
> # (at your option) any later version.

in above-mentioned data/sr.sor?

This should be clarified and license headers/COPYING file(s) added.

Regards,

Rene

**Comment by laszlonemeth** [comment]
I have pushed the following commit:

Disambiguate license: Modified BSD, LGPL-3+ dual-license
    
    for code and language data
    
    and CC-BY-SA/Modified BSD/LGPL-3+ tri-license for Serbian
    
    COPYING: add most permissive modified BSD license


Thanks, László

**Comment by reneengelhard** [comment]
thanks, that makes more sense. Did https://salsa.debian.org/libreoffice-team/libnumbertext/commit/238a6ae2c298b018d2766f9ac868836094d393a1 and https://salsa.debian.org/libreoffice-team/libnumbertext/commit/7c07a68d8e5b813b63d4f82474932f294d57da39
