### ISSUE TITLE
[da] Wrong article before numbers larger than and including one million

### ISSUE THREAD

**Issue by Hsonesson1** [Numbertext/libnumbertext#26]
When I see the numbers spelled out in Danish at https://numbertext.github.io/ all numbers from 100 and up have the article "et" in front of them.

This is wrong. In Danish, the numbers 100 and 1,000 do in fact take the article "et", but all numbers from one million and up take the article "en". 
For example:
1,000,000 = en million
1,000,000,000 = en milliard
1,000,000,000 = en billion
etc.

**Comment by laszlonemeth** [comment]
Fixed in commit 44a07ff9370dd8520ae7de2c400a7de10d70c4af, thanks for your bug report!

**Comment by laszlonemeth** [comment]
Also fixed in the web demo.
