### ISSUE TITLE
Please keep versions and tags in sync

### ISSUE THREAD

**Issue by AMDmi3** [Numbertext/libnumbertext#35]
Versions in [configure.ac](https://github.com/Numbertext/libnumbertext/blob/master/configure.ac#L3) differ from versions in tags and VERSION. From what I can see from commit history

- `1.0.1` — `1.0 beta 2`
- `1.0.2` — `1.0 beta 3`
- `1.0.3` — `1.0`
- `1.0.4` — \<no tag\>

This brings confusion. For instance, many repositories use version from `configure.ac` when packaging [libnumbertext](https://repology.org/metapackage/libnumbertext/versions). I suggest to keep versions everywhere in sync.

**Comment by AMDmi3** [comment]
Ping?

**Comment by laszlonemeth** [comment]
Fixed in the upcoming release 1.0.5. Thanks for your bug report!
