### ISSUE TITLE
LibreOffice 6.1 - could not get to work

### ISSUE THREAD

**Issue by edmundlaugasson** [Numbertext/libnumbertext#37]
Using 64-bit DEB-version of LibreOffice 6.1.0.3, locale in Estonian language.
Checked also https://ask.libreoffice.org/en/question/32783/how-to-use-numbertext-or-moneytext-functions/
Tested also https://ask.libreoffice.org/en/question/1194/convert-numbers-to-english-words/ macro code - did not work in LibreOffice 6.1, quotation marks around cell address, language code or number did not help in formula.

Tried to enter either directly with number or using cell address - always getting error:
`=NUMBERTEXT(5)`
gives
`#VALUE!`
or
`=NUMBERTEXT(A1,en)`
where in A1 is located e.g. number 5, gives
`Err:501`
Well, checked at [https://help.libreoffice.org/Calc/Error_Codes_in_Calc](https://help.libreoffice.org/Calc/Error_Codes_in_Calc) and understood that this function does not respect my separator (comma) and requires semicolon regardless of what is my locale. When used semicolon, will get:
`#NAME?`
... seems that does not recognize the function.
Same happens with _moneytext_ function.
Also very uncomfortable is to enter language codes when the beginning is same with any other function's beginning.
Also did not find the list of used language codes. To be honest, that _=numbertext("help")_ did not work either - so could not get help.

**Comment by laszlonemeth** [comment]
1) You can use the NatNum12 modifier in custom number formatting in LibreOffice, see

https://wiki.documentfoundation.org/ReleaseNotes/6.1#New_.E2.80.9Cspell_out.E2.80.9D_NatNum_modifier
https://help.libreoffice.org/Common/Number_Format_Codes#NatNum_modifiers (NatNum12 hasn't listed, yet).

2) or *install* and use NUMBERTEXT LibreOffice extension from https://extensions.libreoffice.org/extensions/numbertext-1/1.0
(in this release, without Estonian support, yet, so it will return with fall-back language English).

Note: LibreOffice and Numbertext extension will have Estonian support soon, but you can install its datafile (https://github.com/Numbertext/libnumbertext/blob/master/data/et.sor) manually, too, in the LO_installation/share/numbertext path, to get working Estonian number to number name conversion in LibreOffice.

**Comment by edmundlaugasson** [comment]
_[NatNum12 €]0_ gave me e.g. _€ 12_ into cell. Probably did not completely understand that NatNum system. No words. Sounds interesting but not well explained, hard to understand.
That extension seems to be for LibreOffice 6.0 but not for 6.1.

**Comment by laszlonemeth** [comment]
Try [NatNum12 EUR]0 in 6.1.1 or above, or open this file: http://numbertext.org/tmp/numbertext_estonian.ods

Screenshot in LibreOffice 6.2: 
![numbertext_estonian](https://user-images.githubusercontent.com/12903042/46717598-ca730200-cc68-11e8-8f2d-c59ff7402173.png)

**Comment by edmundlaugasson** [comment]
To be honest, the "euroa" is in Finnish language. In Estonian it should be "eurot". Similarly in case of U.S. dollar in plural it is "dollarit" and in singular it is "dollar".
My result in LibreOffice 6.1.1 is different:
![libreoffice_6-1-1_result](https://user-images.githubusercontent.com/6355082/46791810-94a64a00-cd4a-11e8-8e2c-6c41ec964ad1.png)

**Comment by edmundlaugasson** [comment]
... and after adding the [numbertext extension](https://extensions.libreoffice.org/extensions/numbertext-1/1.0), the result is:
![libreoffice_6-1-1_result-with-numbertext](https://user-images.githubusercontent.com/6355082/46792131-48a7d500-cd4b-11e8-9775-c9d172d04608.png)
