### ISSUE TITLE
[fr] Wrong spelling with currency

### ISSUE THREAD

**Issue by armik71** [Numbertext/libnumbertext#41]
Hi
(sorry for my bad english, i'm french)
There's a trouble in french with this :+1: 
300 € : trois cent euros is wrong
trois cent**s** euros is correct
it's the same with 200, 400 500 ...
Thanx for your fantastic work
William

**Comment by laszlonemeth** [comment]
Hi,

Fixed in commit 0b4c47de63ace96bf6516c5081bdab29ec46c1ad

Thanks for your bug report and for your kind words,
László
