### ISSUE TITLE
[it] Wrong ordinal number spelling

### ISSUE THREAD

**Issue by dario-gallucci** [Numbertext/libnumbertext#42]
I have just noticed your library used in libreoffice 6.1.
I would like to point out that some ordinal spelling for italian are incorrect:

- 2nd is secondo (masculine) or seconda (feminine).
1st to 10th are irregular. They are already correct in the library
11 to infinity(?) are regular (remove suffix from cardinal number, add esim-o for masculine and esim-a for feminine)
- 17th is diciassettesimo (m) or diciassettesima (f). This is true for all the following number ending for 7 (37° - trentasettesimo, 47° - quarantasettesimo, 107° - centosettesimo, etc...)
- 18th is diciottesimo (m) or diciottesima (f). Like previous: 38° - trentottesimo, 108° - centottesimo, etc...)
- 19th is diciannovesimo (m) or diciannovesima (f)
- 21st is ventunesimo (m) or ventunesima (f). 31° -> trentunesimo and so on...
- 22nd is ventiduesimo
- 23rd is ventitreesimo
...
- 100th is centesimo
- 101st is cent(o)unesimo
- 102nd is centoduesimo

Thanks for your great job

**Comment by dario-gallucci** [comment]
I realized that also 110° is irregular: centodecimo.
And there are irregular forms for 106, 107, 108 or 109:
- 106° could be centoseiesimo or centosesto.
- 107° could be centosettesimo or centosettimo.
- 108° could be centottesimo or centottavo.
- 109° could be centonovesimo or centonono.

**Comment by dario-gallucci** [comment]
There is a good reference here: [https://en.wikibooks.org/wiki/Italian/Lesson4#Ordinal_numbers](url)

**Comment by laszlonemeth** [comment]
Fixed in commit a3efaddf686cf5f06a3dec040ed65ec50432df72

Thanks for your bug report and for your kind words,
László
