### ISSUE TITLE
[ja] Wrong character for negative number

### ISSUE THREAD

**Issue by cmplstofB** [Numbertext/libnumbertext#50]
In Japanese, the character which means negative is “負 ([U+8CA0](https://unicode.org/cldr/utility/character.jsp?a=8CA0)),” not “负 ([U+8D1F](https://unicode.org/cldr/utility/character.jsp?a=8D1F)).”
The wrong character is used at [this data](https://github.com/Numbertext/libnumbertext/blob/master/data/ja.sor#L31).

Would you please fix it?

![numexpr_negative_ja](https://user-images.githubusercontent.com/20594300/51785294-d42d6080-2198-11e9-847f-3c16d3aecf99.png)

**Comment by laszlonemeth** [comment]
Fixed in the source tree:

https://github.com/Numbertext/libnumbertext/commit/9f5844545c994fcbc870463889844e3cb148a32d

Thanks for your report,
László
