### ISSUE TITLE
some gaps in Latvian

### ISSUE THREAD

**Issue by andritis** [Numbertext/libnumbertext#51]
some gaps in Latvian
extension moneytext is required.
But not for routine office routine.
Your version contains unnecessary letters "i".
I hope the table will help you understand the problem.
![ekranattels 2019-01-30 13-53-01](https://user-images.githubusercontent.com/1977879/51979670-7057b000-2496-11e9-98fb-a113543eca90.png)

**Comment by laszlonemeth** [comment]
Fixed in commit 163afea3335546c971584338b1aa4a56b941bc80. Thanks for your detailed bug report. László
