### ISSUE TITLE
[th] Wrong handling of decimal in currency conversion

### ISSUE THREAD

**Issue by nicorobinhood** [Numbertext/libnumbertext#64]
Conversion of currency with decimals in Thai Baht seems to ignore the last zero. The regular number conversion handle this correctly.

Example of number conversion, which already handle this correctly:

- 1.05 = หนึ่งจุดศูนย์ห้า
- 1.50 = หนึ่งจุดห้า

Example of currency conversion:

- THB 1.05 = หนึ่งบาทห้าสตางค์ <= This is correct
- THB 1.50 = หนึ่งบาทห้าสตางค์ <= This is wrong. It should be หนึ่งบาทห้าสิบสตางค์

Tested with LibreOffice extension which I **built myself using latest code 2 days ago**. I didn't use the current official release which is almost a year old. I would fix and test the code myself if I know how to test the sorting algorithm without having to build the extension every time. I welcome any advice. Thank you.

**Comment by laszlonemeth** [comment]
Hi,
I've updated the web site, so you can use the following web editor of Soros language. You can load Thai (th) module using the pop-up menu of page: 

https://numbertext.github.io/Soros.html

**Comment by nicorobinhood** [comment]
The issue has been fixed and merged into the base code.
