### ISSUE TITLE
Wrong Euro cents translation in Ukrainian

### ISSUE THREAD

**Issue by kty0mka** [Numbertext/libnumbertext#74]
In Ukrainian, eurocents should be in the genitive case "цент**і**в", not "цент**о**в" - just like cents for US dollars.

**Comment by laszlonemeth** [comment]
Dear  Kty0mka,

Many thanks for reporting the problem. Fixed in the commit https://github.com/Numbertext/libnumbertext/commit/21cc2f78cc93206e5d364a64adb808a0a5fb133f.

László
