### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by pintert3** [Numbertext/libnumbertext#78]
It appears the documentation for adding new languages is outdated. With the exception of the first step, it seems everything after doesn't make sense.(I'm referring to the **doc/addnewlocale.txt**. I was trying to add a language and I'm not sure if adding the locale file in the `data` directory is sufficient.

**Comment by laszlonemeth** [comment]
Dear Pintert3,

I've updated the documentation here:

https://github.com/Numbertext/libnumbertext/blob/master/doc/addnewlocale.txt

Thanks for your bug report,
László
