### ISSUE TITLE
Ukrainian Text for numbers ending with "1" or "2" is wrong.

### ISSUE THREAD

**Issue by rybaryba0** [Numbertext/libnumbertext#81]
MONEYTEXT wording for UAH currency in Ukrainian language is wrong.
CORRECT: 101,00 = сто **одна** гривня
CURRENTLY (OpenOffice Extension v.1.0.5.) = сто **один** гривня 

CORRECT: 102,00 = сто **дві** **гривні**
CURRENTLY (OpenOffice Extension v.1.0.5.) = сто **два** **гривня**

**Comment by burunduk** [comment]
Fixed in 1.0.7

**Comment by laszlonemeth** [comment]
Hi, thanks for the fix (see pull request #68 from contributorpw/patch-rub-uah) and its verification, László
