### ISSUE TITLE
Polish ordinal form 20 to 29 is wrong

### ISSUE THREAD

**Issue by Gabryha** [Numbertext/libnumbertext#85]
Hi.
In Polish lang. numbers from 20 to 29 is wrong converted
20 - is dwadziesty - will be dwudziesty
2X - is dwadzieścia xxxx - will be dwudziesty xxxx

I made test on https://numbertext.github.io/Soros.html
adding this two lines after first 3 lines in section == ordinal ==
correcting wrong polish translation/convertion for range 20-29 (and +N * 100 range too)

"(.*)dwadzieścia (.*)"	$(ordinal \2dwudziesty \3)
(.*)dwadzieścia	\2dwudziesty

and second:
Section ordinal is marked as (masculine)? - YES it's correct, it is masculine.

**Comment by laszlonemeth** [comment]
Dear Gabryha,

Fixed in https://github.com/Numbertext/libnumbertext/commit/721c60a86e683112adab00341aa9934967d3769f
Updated library will be released this year with your fix.

Thanks for your help and Best regards,
László
