### ISSUE TITLE
Language Marathi is missing from Libreoffice extension

### ISSUE THREAD

**Issue by shantanuo** [Numbertext/libnumbertext#86]
I have downloaded the calc extension from:
https://extensions.libreoffice.org/en/extensions/show/numbertext-1

The language Marathi is not available in the extension. But it seems to be listed in the github readme.

**Comment by laszlonemeth** [comment]
Numbertext library is integrated with LibreOffice. You can use NatNum12 modifier to get Numbertext and Moneytext with arbitrary capitalization, also in Marathi, see chapter NatNum12 here:

https://help.libreoffice.org/7.1/en-US/text/shared/01/05020301.html

**Comment by shantanuo** [comment]
Yes, It is built-in. Closing the issue.
